language: node_js
node_js:
  - "0.10.40"
  - "0.11.16"
  - "0.12.7"
  - "iojs"
  - "4.0.0"
  - "4.1.2"
  - "4.2.6"
  - "5.0"
  - "5.1"
  - "5.5"

before_script:
  - npm run lint

script:
  - npm run test

sudo: false

notifications:
  email:
    - juan@altairstudios.es

git:
  depth:
    10

cache:
  directories:
    - node_modules

os:
  - linux